name: ecomly
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.0
  go_router: ^12.1.1
  flutter_riverpod: ^2.4.8
  riverpod_annotation: ^2.3.2
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  device_preview: ^1.1.0
  gap: ^3.0.1
  country_picker: ^2.0.22
  flutter_multi_formatter: ^2.12.0
  collection: ^1.17.2
  pin_code_fields: ^8.0.1
  iconly: ^1.0.1
  curved_navigation_bar: ^1.0.3
  iconify_flutter: ^0.0.5
  lottie: ^2.7.0
  carousel_slider: ^5.0.0
  infinite_scroll_pagination: ^4.0.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  flutter_rating_stars: ^1.0.3+4
  webview_flutter: ^4.4.0
  url_launcher: ^6.2.3
  image_stack: ^2.1.1
  flutter_animate: ^4.4.0
  timelines: ^0.1.0

  stomp_dart_client: ^2.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
  riverpod_lint: ^2.3.6
  riverpod_generator: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer-Black.otf
        - asset: assets/fonts/Switzer-BlackItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Bold.otf
        - asset: assets/fonts/Switzer-BoldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Extrabold.otf
        - asset: assets/fonts/Switzer-ExtraboldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Extralight.otf
        - asset: assets/fonts/Switzer-ExtralightItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Italic.otf
          style: italic
        - asset: assets/fonts/Switzer-Light.otf
        - asset: assets/fonts/Switzer-LightItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Medium.otf
        - asset: assets/fonts/Switzer-MediumItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Regular.otf
        - asset: assets/fonts/Switzer-Semibold.otf
        - asset: assets/fonts/Switzer-SemiboldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Thin.otf
        - asset: assets/fonts/Switzer-ThinItalic.otf
          style: italic
